name: Deploy GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify HTML files exist
        run: ls *.html  # Simple check to confirm the files are present

      - name: Upload HTML files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Upload the entire repo root
          # Exclude everything except HTML files
          exclude: |
            *
            !*.html
          retention-days: 1

      - name: Deploy
        uses: actions/deploy-pages@v3