name: Deploy GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List all files in root
        run: ls -a

      - name: Upload HTML files
        uses: actions/upload-pages-artifact@v3
        with:
          path: './*.html' # Explicitly look in the current directory

      - name: Deploy
        uses: actions/deploy-pages@v3