name: Deploy GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload HTML files
        uses: actions/upload-pages-artifact@v3
        with:
          path: '*.html'  # Explicitly uploads only HTML files

      - name: Deploy
        uses: actions/deploy-pages@v3