name: Deploy GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write       # needed by configure-pages & deploy-pages
      id-token: write    # needed by configure-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify HTML files exist
        run: ls *.html

      - name: Upload HTML files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .                 # repo root
          exclude: |
            *
            !*.html

      - name: Configure Pages
        uses: actions/configure-pages@v2

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        # (no additional inputs needed)